using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerStateMachine : MonoBehaviour
{
    public PlayerState currentState;

    public PlayerController playerController;
    // Start is called before the first frame update
    void Start()
    {
        TransitionToState(new IdleState(this));
    }

    // Update is called once per frame
    void Update()
    {
        if (currentState != null)
        {
            currentState.Update();
        }
    }
    private void FixedUpdate()
    {
        if (currentState != null)
        {
            currentState.FixedUpdate();
        }
    }

    public void TransitionToState(PlayerState newState)
    {
        if(currentState?.GetType()==newState,GetType())
        {
            return;
        }

        currentState?.Exit();
        currentState = newState;
        currentState.Enter();
        Debug.Log($"Transitioned to State {newState.GetType().Name}");
    }
}
